from pydantic import BaseModel, Field
from typing import List, Literal

class QuestionnaireAnswers(BaseModel):
    """Defines the structure for the user's questionnaire answers."""
    destination: str
    trip_type: Literal['Relaxation', 'Adventure', 'Cultural', 'Romantic'] = Field(..., alias='tripType')
    interests: List[str]
    budget: Literal['Budget-friendly', 'Mid-range', 'Luxury']

class UserProfile(BaseModel):
    """Represents the user's taste profile stored in Firestore."""
    user_id: str
    answers: QuestionnaireAnswers
    taste_profile_summary: str # A summary generated by an LLM

class DailyPlan(BaseModel):
    """A single day in the itinerary."""
    day: int
    activities: List[str]
    explanation: str

class Itinerary(BaseModel):
    """The final itinerary structure."""
    title: str
    description: str
    daily_plan: List[DailyPlan]
    budget: str
    booking_url: str = "#"

class ItineraryGenerationRequest(BaseModel):
    """Request model for the itinerary generation endpoint."""
    user_id: str # To fetch the user's profile
    answers: QuestionnaireAnswers

class ItineraryGenerationResponse(BaseModel):
    """Response model for the itinerary generation endpoint."""
    itineraries: List[Itinerary]
